### ISSUE TITLE
Handle unwanted disconnections

### ISSUE THREAD

**Issue by lieuwex** [tomsmeding/pointit#1]
I mean like when the connection breaks, we have to just join back like nothing happened.

**Comment by tomsmeding** [comment]
And what if the user just quits without saying anything?

**Comment by lieuwex** [comment]
Uhmm well yeah we use a heartbeat to check if the connection went down. So the idea is to just keep the player in the room, i guess. With a flag of something like 'disconnected' then the client sends a key or smth to tell they're the same person.

**Comment by lieuwex** [comment]
I think that will just be a 25 char uid something, maybe a bit overkill but why not :p

**Comment by lieuwex** [comment]
We also need to think about how to handle when the user rejoins mid-game, how do we want to structure the code to handle that? The easiest way is to just show on the client something like 'waiting for the next round?'

**Comment by tomsmeding** [comment]
Seems reasonable.

**Comment by lieuwex** [comment]
25505a272df9b387b2ae6a1141afb0901003586d

**Comment by tomsmeding** [comment]
That's quite a diff
